Repository lucasvieirasilva/nx-plugins, pull requests merged in 2023-11, with the labels that each got.

#185 feat(nx-python): add ruff check executor and project generator
  e2e/nx-python-e2e/jest.config.ts
  e2e/nx-python-e2e/tests/__snapshots__/nx-python.spec.ts.snap
  e2e/nx-python-e2e/tests/nx-python.spec.ts
  packages/nx-python/README.md
  packages/nx-python/executors.json
  packages/nx-python/src/executors/ruff-check/executor.spec.ts
  packages/nx-python/src/executors/ruff-check/executor.ts
  packages/nx-python/src/executors/ruff-check/schema.d.ts
  packages/nx-python/src/executors/ruff-check/schema.json
  packages/nx-python/src/generators/poetry-project/__snapshots__/generator.spec.ts.snap
  packages/nx-python/src/generators/poetry-project/files/base/pyproject.toml
  packages/nx-python/src/generators/poetry-project/generator.spec.ts
  packages/nx-python/src/generators/poetry-project/generator.ts
  packages/nx-python/src/generators/poetry-project/schema.d.ts
  packages/nx-python/src/generators/poetry-project/schema.json
Labels: enhancement

#186 feat(nx-python): add `projectNameAndRootFormat` parameter to poetry project generator
  e2e/nx-python-e2e/tests/nx-python.spec.ts
  packages/nx-python/README.md
  packages/nx-python/src/generators/poetry-project/__snapshots__/generator.spec.ts.snap
  packages/nx-python/src/generators/poetry-project/generator.spec.ts
  packages/nx-python/src/generators/poetry-project/generator.ts
  packages/nx-python/src/generators/poetry-project/schema.d.ts
  packages/nx-python/src/generators/poetry-project/schema.json
  packages/nx-python/src/migrations/update-16-1-0/replace-nx-run-commands.spec.ts
Labels: bug, enhancement

#184 fix(nx-python): handle "from" for packages in pyproject.toml during the build process
  packages/nx-python/src/executors/build/executor.spec.ts
  packages/nx-python/src/executors/build/resolvers/utils.ts
  packages/nx-python/src/graph/dependency-graph.ts
Labels: bug
