Repository lucasvieirasilva/nx-plugins, pull requests merged in 2023-02, with the labels that each got.

#39 chore(workspace): upgrade nx version to 15.6.3
  package-lock.json
  package.json
Labels: dependencies

#24 feat(nx-python): added support for build with non-locked versions and non-bundle local dependencies
  packages/nx-python/README.md
  packages/nx-python/src/executors/build/executor.spec.ts
  packages/nx-python/src/executors/build/executor.ts
  packages/nx-python/src/executors/build/resolvers/index.ts
  packages/nx-python/src/executors/build/resolvers/locked.ts
  packages/nx-python/src/executors/build/resolvers/project.ts
  packages/nx-python/src/executors/build/resolvers/types.ts
  packages/nx-python/src/executors/build/resolvers/utils.ts
  packages/nx-python/src/executors/build/schema.d.ts
  packages/nx-python/src/executors/build/schema.json
  packages/nx-python/src/executors/tox/executor.spec.ts
  packages/nx-python/src/executors/tox/executor.ts
  packages/nx-python/src/generators/migrate-to-shared-venv/generator.spec.ts
  packages/nx-python/src/generators/project/__snapshots__/generator.spec.ts.snap
  packages/nx-python/src/generators/project/generator.spec.ts
  packages/nx-python/src/generators/project/generator.ts
  packages/nx-python/src/generators/project/schema.d.ts
  packages/nx-python/src/generators/project/schema.json
  packages/nx-python/src/graph/dependency-graph.ts
Labels: enhancement

#41 feat(nx-python): adds support for custom dependency sources
  packages/nx-python/README.md
  packages/nx-python/src/executors/build/executor.spec.ts
  packages/nx-python/src/executors/build/executor.ts
  packages/nx-python/src/executors/build/resolvers/project.ts
  packages/nx-python/src/executors/build/resolvers/types.ts
  packages/nx-python/src/executors/build/schema.d.ts
  packages/nx-python/src/executors/build/schema.json
  packages/nx-python/src/graph/dependency-graph.ts
Labels: enhancement

#52 chore(workspace): migrate nx from 15.6.3 to 15.7.2
  .eslintignore
  package-lock.json
  package.json
  packages/nx-python/src/graph/dependency-graph.spec.ts
Labels: dependencies

#54 fix(nx-python): replace rmSync to fs-extra removeSync and add fs-extra as a dependency
  package-lock.json
  package.json
  packages/nx-python/src/executors/build/executor.ts
  packages/nx-python/src/executors/build/resolvers/utils.ts
  packages/nx-python/src/executors/sls-deploy/executor.ts
  packages/nx-python/src/executors/sls-package/executor.ts
Labels: bug
